name: gofmt and lint

on:
  pull_request:
    branches:
      - master

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-path: './frontend'
          gofmt-flags: '-l -d'
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
          working-directory: frontend
